### ISSUE TITLE
在centos7上面一跑就奔溃了

### ISSUE THREAD

**Issue by chrisforbt** [LittleLiByte/lua-rsa#1]

**Comment by LittleLiByte** [comment]
可以看到错误日志吗，这个库我放在ubuntu上面运行时没问题，并且也已经用到了项目中

**Comment by chrisforbt** [comment]
那就是rsa.so这个库位置没有放对，你可以查下centos的.so库一般是放到哪个目录下的，因为我只在ubuntu下测试使用，所以并不是很清楚centos的存放位置，所以找不到rsa.so很正常。抱歉，这么久才回复你。
----------
日志显示的获取rsa失败。

在 2016-12-21 19:56:23，"李志杰" <notifications@github.com> 写道：


可以看到错误日志吗，这个库我放在ubuntu上面运行时没问题，并且也已经用到了项目中
